name: Improvement
description: Suggest improvements to existing functionality
title: "[Improvement]: "
labels: ["improvement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest improvements to existing features or code quality.

  - type: dropdown
    id: type
    attributes:
      label: Improvement Type
      description: What type of improvement is this?
      options:
        - Code Refactoring
        - Performance Optimization
        - Documentation
        - Test Coverage
        - Developer Experience
        - Accessibility
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the codebase does this affect?
      options:
        - Frontend (React Components)
        - Backend (API Routes)
        - Electron Main Process
        - Core Domain
        - Adapters/Infrastructure
        - Hooks
        - Types
        - Build/Configuration
        - Documentation
        - Tests
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current State
      description: Describe the current implementation or behavior
      placeholder: Currently, the code does...
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Improvement
      description: Describe the improvement you're suggesting
      placeholder: The improvement would...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits would this improvement bring?
      placeholder: |
        - Better performance
        - Cleaner code
        - Easier maintenance

  - type: textarea
    id: files
    attributes:
      label: Affected Files
      description: List specific files that would need to be modified
      placeholder: |
        - frontend/core/application/ConfigService.ts
        - frontend/hooks/useConfig.ts

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much effort do you think this would take?
      options:
        - Small (< 1 hour)
        - Medium (1-4 hours)
        - Large (1-2 days)
        - Extra Large (> 2 days)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked that this improvement hasn't been suggested before
          required: true
        - label: I would be willing to contribute to implementing this improvement
